# Generated by Django 5.2 on 2025-04-23 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='faculty',
            field=models.CharField(choices=[('IT-Business', 'IT-Business'), ('Business', 'Business'), ('HR-manager', 'HR-manager'), ('Graphic-Design', 'Graphic-Design'), ('Marketing', 'Marketing')], default='IT-Business', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='score',
            field=models.IntegerField(),
        ),
    ]
